#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi
										#este es bibtex
latex heterogeneous.tex && latex heterogeneous.tex &&  latex heterogeneous.tex && latex heterogeneous.tex && latex heterogeneous.tex && latex heterogeneous.tex && latex heterogeneous.tex && echo "-----------------------------" && dvips heterogeneous.dvi -o && ps2pdf heterogeneous.ps && echo " "
